name: Scrapper CI with Maven

on:
  push:
    branches: [ "master" ]
    paths:
      - 'scrapper/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'scrapper/**'

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Java setup
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn package -pl scrapper -am

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the scrapper Docker image
        run: |
          docker build -t ghcr.io/gadetych/tinkoff-project/scrapper:latest scrapper/.
          docker push ghcr.io/gadetych/tinkoff-project/scrapper:latest

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkstyle with Maven
        run: mvn -pl scrapper -am checkstyle:check
